export  default  [
      {
        "id": "1",
        "name": "Andaman",
        "capital": "Port Blair",
        "about": "The Andaman and Nicobar Islands located in the east of the Indian mainland geographically, float in splendid isolation in the Bay of Bengal. Once a hill range extending from Myanmar to Indonesia, these picturesque undulating islands, islets numbering around 572, are covered with dense rain-fed, damp and evergreen forests and endless varieties of exotic flora and fauna. Most of these islands (about 550) are in the Andaman Group, 28 of which are inhabited. The smaller Nicobars, comprise some 22 main islands (10 inhabited). The Andaman and Nicobars are separated by the Ten Degree Channel which is 150 Kms. wide.",
        "climate": "The islands have a tropical climate. The South-west Monsoon sets in Andaman Nicobar islands towards the end of May and the North-east Monsoon in November. There is no fury of hot summer, no chilling winter, no water clogging or traffic jams. For those who want to enjoy boating, swimming, snorkeling, sightseeing all 12 months is season. North Indians find relief from burning heat and chilling winter if they visit the island from May/June/July and in December/January. Season for nature lovers is May to December when forest is lush green and waterfalls are at their prime. Divers can enjoy the best during December to April and bird watchers during winter times.",
        "history": "The Andaman & Nicobar Islands have been inhabited for several thousand years, at the very least. The earlier archaeological evidence yet documented goes back some 2,200 years; however, the indications from genetic, cultural and linguistic isolation studies point to habitation going back 30,000 – 60,000 years, well into the Middle Palaeolithic. In the Andaman Islands, the various Andamanese people maintained their separated existence through the vast majority of this time, diversifying into distinct linguistic, cultural and territorial groups.",
        "time": "Andaman has a moderate temperature all through the year within the range of 23°C to 31°C. It has a tropical climate. There are no severe climate conditions except for tropical storms and rains in late summers and monsoons.Summers (March to May) are warm but pleasant with sea breeze and have humidity level about 80%. It is suitable for all kinds of tourist activities.",
        "food": "The cuisine Of Andaman is like the island itself-tropical, exotic and refreshing. The sea that is all around has a defining effect on the island's culture, livelihood and cuisine. There is little here, in which you will not find traces of the sea. The food here, hence, is dominated by seafood preparations and you don't want to miss the fish delicacies here. Other than seafood too, the staple diet is essentially non-vegetarian.However, as the island is becoming an increasingly popular tourist spot, the resorts and other eating places will give you options of Indian, Chinese and a few more cuisines.Also, the fruits here are popular and refreshing. You can find Mangoes, Bananas, Pineapples, Guava and more. One can also sip in the truly refreshing and tropical coconut water here.",
        "img": "https://bit.ly/2qTdWTu"
      },
      {
        "id": "2",
        "name": "Punjab",
        "capital": "Chandigarh",
        "about": "Deriving its name from five full-bodied rivers–Sutlej, Beas, Ravi, Jhelum, and Chenab–which flow through its vast plains, Punjab is representative of abundant things. Located on the north-western edge of India, it is one of the smaller albeit prosperous states of the nation, and home to a lively, hospitable and dynamic people. Widely acknowledged as the cradle of civilization, it is a land of ethnic and religious diversity, having borne and shaped a number of religious movements that include Sikhism, Buddhism and Sufism. The Punjabi language, too, finds its origin in the Indo-European linguistic family that includes Persian and Latin.",
        "climate": "The Summer in Punjab actually commences from mid April but the temperature starts rising from February onwards. Rainfall ranges from 250mm to 1000mm. Agriculture in the state highly depends on the rains. The winter season in Punjab is mostly experienced in the month of January, when the temperature falls to 5°C in the night and hovers around 12°C in the day. In the post winter transitional season, hail-storms and brief showers occur which cause damage to the crops. The wind becomes dry by the end of March. The Punjab climate has been a significant factor in shaping the economy of the state.",
        "history": "The history of Punjab goes back thousands of years. Undivided Punjab has been the cradle of the Indus Valley Civilization, the remains of which can be seen at the Ropar archaeological site and its dedicated museum. This fertile ancient land finds mention even in Mahabharata and Ramayana. Infact it is believed that the Ramayana was written here by Valmiki ji. Places like Rupnagar, Kiratpur, Dholbaha, Rohira and Ghuram...all in Punjab; have unearthed artifacts that date back centuries. In Sanghol are 107 statues of the Kushan period evoking memories of a flourishing Buddhist monastery. This monastery was visited by Hiuen Tsang in the 7th century.",
        "time": "The best time to visit Punjab is in the spring, from February to April, and in the autumn, from September to November.",
        "food": "Punjab is synonymous to food and incomplete without its mouthwatering delicacies. Rich in colour, ingredients, spices and the most elaborate and grand cooking styles, Punjabi food derives several elements of its cuisine from Pakistan, the then undivided Punjab.The national cuisine borrows some of its most popular and lip-smacking items from Punjab's menu from Paratha, Tandoori Chicken, Naan, Pakodas to delicacies of Paneer. The food here represents a particular festivity, vibrancy and cultural richness in every day, a big part of which revolves around having good and rich food. There is also an almost perfect balance between the vegetarian and non-vegetarian choices, the options being equally irresistible for both. Punjabi cuisine is nearly identified with generous use of 'Ghee' or butter to give the food a rich flavour. Also onion, ginger, garlic and strong spice leave strong and distinct flavours in the menu here. Butter Chicken, Tandoori Chicken, Shahi Paneer, Chole Bhature, Makki di roti, Sarson da Saag, Dal fry, Amritsari fish, Aloo gobhi, Rajma Chawal, Punjabi Kadhi, Lassi are the dishes that define the food here, and the list is almost infinite. Gajar ka Halwa, Jalebi, Kulfi, Rabri, Gulab Jamun, Barfi, Motichoor Laddo are also equally tempting traditional sweets in the area.",
        "img": "https://bit.ly/2XjaMVx",
          },
      {
        "id": "3",
        "name": "Rajasthan",
        "capital": "Jaipur",
        "about": "Recognized as the \"Land of Kings\" and having sheer variety of experiences to offer, Rajasthan is the largest state of India located on the northwestern side and is one of India's most popular tourist destinations.\nSteeped in tales of chivalry and romance, also famous for striking desert landscape, massive forts, mesmerizing lakes and fabulous palaces, Rajasthan represents the quintessential India. Also, the crafts and folk arts originated here are world famous.With the legendary cities of Jaipur, Udaipur, Jaisalmer, and Jodhpur, built by the Rajput warriors, and the artisan communities and indigenous tribal, Rajasthan is a unique combination of royal and tribal India. Rajputs ruled the Land of Royalty for a long time and till today they are regarded in very high esteem.",
        "climate": "Summers in Rajasthan last from April to June and are particularly harsh with temperatures rising up to 48°C during the day. That being said, if you do plan to visit Rajasthan in the summer, head to places like Mount Abu, Kumbhalgarh or Ranakpur. The weather here is pleasant and the views offered are breath-taking. For other cities, the weather is optimal in the early evenings for roaming around outside in the early mornings and late evenings, and it is advisable to stay indoors otherwise.Monsoon is a far more pleasant experience, the temperatures tend to drop across the state and the rain showers transform the arid landscape of Rajasthan. July to September is a particularly good time to visit if you wish to avoid the crowds you'd usually find during peak tourist season. Bundi, the lake city of Udaipur and the Keoladeo National Park are picturesque and are a must visit if you plan to travel to Rajasthan during the Monsoon.",
        "history": "The state of Rajasthan in India has a history dating back thousands of years. It was the site of the Indus Valley Civilization. The early medieval period saw the rise of the Mughal Empire. The Mughals granted high positions to Rajput rulers who allied with them. However, some Rajput kingdoms did not accept Mughal suzerainty and were constantly at war with them. The Mughal rule effectively ended in the 18th century, when the Maratha Empire conquered much of the subcontinent.\n\nMaratha rule was soon replaced by British rule in India. The British also made allies out of local rulers, who were allowed to rule their princely states. This period was marked by famines and economic exploitation. However, the British period also saw the growth of railways, telegraph and modern industry in the region. After Indian Independence in 1947, the various princely states of Rajasthan were integrated into India.",
        "time": "The temperatures continue to drop once the monsoon has passed, and come October winter sets in that lasts till March. During December and January, there can be a severe variation in temperatures during the day and the night. In fact, temperatures are known to drop as low as 0°C and below. This is the best time to visit Rajasthan as the desert sun is not as intense and the days are pleasant. Most of the festivals held in winter are planned as tourist attractions, with visitors coming in from different parts of the world.",
        "food": "Rajasthanis love their food which can be evidenced in the time and energy they put into their preparations. The cuisine of Rajasthan is primarily vegetarian and offers a fabulous variety of mouthwatering dishes. The food here is such that it is suitable for the weather, availability of water, and other environmental factors of the area. Rajasthan is much of what its culture is, and the culture here derives a lot of its colour, festivity, significance and of course, spice, often literally from the diverse and exquisite cuisine here. The delicacies of the state are indeed some of the richest, unique and most loved preparations of India. Names such as Dal Bati Churma, Moong Dal ka Halwa, Ghevar, Rabdi and numerous more are popular all across, especially in North India, with their popularity spreading beyond the confines of the state, Your trip might be incomplete if you don't try the scrumptious dishes that the land has to offer, especially the Rajasthani thali. ",
        "img":"https://upload.wikimedia.org/wikipedia/commons/0/09/Thar_Khuri.jpg",
      },
     {
        "id": "4",
        "name": "Kerala",
        "capital": "Thiruvananthapuram,",
        "about": "Kerala - home to the languid backwaters, long coastlines, sprawling tea gardens, and colourful dance forms, is also famously known as 'God?s Own Country'. Located on the Malabar coast of Southern India, it is a tiny sliver of paradise that is also one of the best tropical tourist destinations one can look for. Whether you want to bask in the sun and sand of the palm tree-lined Kovalam beach or want to take a hike to Munnar hill station, or even if you're going to walk down the bustling streets of Kochi, Kerala has everything on offer to take your pick from!The land of literate and simple citizens, Kerala amuses you with its spectacular dance forms, music and handicrafts. Considered to be one among the ten paradises of the world, Kerala is known for long palm tree beaches, beautiful rivers, pious inland water bodies and a calm, green atmosphere.",
        "climate": "The coastal state of Keralalying on the Southwestern tip of India has commonly been called the tropical paradise of India. Bounded by Arabian Sea at one side and the Western Ghats on the other, the beautiful land with stunning beauty has an equable and tropical climate offering a pleasing atmosphere throughout the entire year. This coastal state has hot and humid climate during April-May and pleasant, cold climate in December-January. Summer extends from the month of April to June when the temperature reaches to a maximum of 33 degrees centigrade. Summer is followed by South West Monsoon that starts pouring in the month of June and continues till September. With the arrival of winter there is certain drop in the temperature and you can feel a slight chill due to the cold wind. Winter in Kerala lasts from from November to January or February.",
        "history": "According to the Tamil classic Purananuru, the Chera king Senkuttuvan conquered the lands between Kanyakumari and the Himalayas.[25] Lacking worthy enemies, he besieged the sea by throwing his spear into it.[25][26] According to the 17th century Malayalam work Keralolpathi, the lands of Kerala were recovered from the sea by the axe-wielding warrior sage Parasurama, the sixth avatar of Vishnu (hence, Kerala is also called Parasurama Kshetram 'The Land of Parasurama'[27]). Parasurama threw his axe across the sea, and the water receded as far as it reached. According to legend, this new area of land extended from Gokarna to Kanyakumari.[28] The land which rose from sea was filled with salt and unsuitable for habitation; so Parasurama invoked the Snake King Vasuki, who spat holy poison and converted the soil into fertile lush green land. Out of respect, Vasuki and all snakes were appointed as protectors and guardians of the land.",
        "time": "The Best time to visit Kerala is Winter Season between September and March when the Kerala has comfortable climate and pleasant weather with less humidity in all the tourist places. People who are looking for ayurvedic treatments prefer Monsoon season from June to August",
        "food": "Kerala cuisine is a combination of vegetables, meats and seafood flavoured with a variety of spices. One can notice the dominance of rice, coconut, seafood and variety of non-vegetarian dishes and the lavish use of spices like Pepper, Cardamom, Cloves, Ginger and chillies that add to the taste and flavour of Kerala's traditional food.With the Romans, Greeks, Dutch, Portuguese and many more invaders making their way to the ports of Kerela, it's no surprise that Kerala's food is so diverse and distinct from the rest of the country. There are differences seen in the taste and styles of north and south Kerala- the menu ranges from lip-smacking Mappila biryani, Sadya and brilliant non-vegetarian dishes, you are sure to find something new every day! Kerala is a paradise for seafood lovers; from an array of prawns, lobsters, rockfish and squid among the others, the place won't disappoint you. The Sadya is a substantial feast served on a banana leaf and consists of 24-28 dishes in a single meal. Onam Sadyas are something you should try if you're in Kerala. Other favourite dishes include Avial, Kozhikodan Halwa, Appam-stew combo, Kappa, Puttu-Meen curry and Paal Payasam. ",
        "img":"https://www.holidify.com/images/bgImages/KOCHI.jpg",
     },

         
       
    
      {
        "id": "5",
        "name": "Maharashtra",
        "capital": "Mumbai",
        "about": "Maharashtra, the land of everything unlimited invites you into its widespread plethora of attractions. It is adorned by the beautiful Sahyadri ranges of the Western Ghats with high mountains that disappear into the morning mist, while the sprawling belt of the Konkan Coast mesmerises the eyes by its white beaches. The ruins of the ancient forts and palaces in Pune and Ratnagiri among others proudly narrates the story of the then mighty rulers of Maharashtra. Centuries-old temples situated in places like Pandharpur, Ozar are still rooted in their traditions, offering sanctuary to pilgrims. As do the small hill stations of Mahabaleshwar, Lonavala, Matheran, nestled cosily in nature, provide respite to travellers from the hustle and bustle of the cities.Often called the 'Gateway to the Heart of India', Maharashtra is the third largest state and second most populous state than in the country. Owing to its proximity to the Western Ghats, it is blessed with a picturesque backdrop of the mountains on one side and has the beautiful Konkan coastal belt on the other.",
        "climate": "Summer: March, April and May are the hottest months. During April and May thunderstorms are common all over the state. Temperature varies between 22°C-39°C during this season.\nRainy: Rainfall starts normally in the first week of June. July is the wettest month in Maharashtra, while August too gets substantial rain. Monsoon starts its retreat with the coming of September from the state\nWinter: Cool dry spell, with clear skies gentle breeze and pleasant weather prevails from November to February. But the eastern part of Maharashtra sometimes receives some rainfall. Temperature varies between 12°C-34°C during this season\n",
        "history": "The modern state of Maharashtra is bordered by the Arabian Sea to the West, Gujrat and the Union Territory of Dadara Nagar haveli to the North West,Madhya Pradesh to the North & North East, Chhattisgadh to the East, Karnataka to the South, Andhra Pradesh to the South East and Goa to the South West.The antiquity of the human habitation in the state goes back to the stone age period (1.27 million years ago). Numerous sites with the stone age tools have been reported on the bank of various rivers as well as in the river vallies. Numerous Chalcolithic sites have been located and some like Inamgaon(1300 BCE to 700 BCE) were extensively excavated.",
        "time": "There is no particular best time to explore the state since the eevry season has its own pros and cons. However, winters are most suitable since the weather remains calm and pleasant. Summers are too scorching but are perfect to visit hilly regions. In monsoons also, heavy downpours are observed but, rains add to the beauty of mountainous areas.",
        "food": "Maharashtrian cuisine is one which can tickle and surprise your taste buds. The food ranges from mild to really spicy food as well as flattering deserts that you will love to indulge in. Vada Pav (Potato filled cutlets with Buns), Misal (A spicy gravy of pulses garnished with onions), Onion fries, etc. are the everyday food of the people here and are items with which the state cuisine is identified.The staple diet of Maharashtra includes rice, Dal, chapattis and a vegetable dish generally accompanied by pickle for taste. An eclectic and vibrant mix of cultures derived from the people with diverse backgrounds who move here, gives the cuisine here countless varieties, with absolutely nothing that you cannot find here. Each of these varied and colourful elements and cuisine styles finds themselves a unique place in the state's menu. Typically, a South-Indian breakfast will lead to a Maharashtrian lunch, a Gujarati snack and end with a Punjabi Dinner. Add a Bengali sweet if you want. This is how Maharashtra borrows food cultures from all over and makes them its own.",
        "img":  "https://www.tripsavvy.com/thmb/sOKirs6tks8NcKlhytwechtqOm4=/4241x2386/smart/filters:no_upscale()/GettyImages-1008831236-5c65d6bf4cedfd00014aa310.jpg",
       
      },
    ]
        
          